# Generated by Django 4.2.2 on 2023-06-20 14:50

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.CharField(default=api.helpers.getdate, max_length=100),
        ),
    ]
